spring.application.name=PaperlessRest

# We use 8081, not the Spring Boot default 8080, because the project's architecture diagram fixes PaperlessREST to run on port 8081.
server.port=8081

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:paperless}
spring.datasource.username=${DB_USER:paperless}
spring.datasource.password=${DB_PASSWORD:paperless}

# Hibernate reads @Entity classes and creates/updates the matching database tables automatically.
spring.jpa.hibernate.ddl-auto=update

# Prints every SQL statement Hibernate generates into the console. Very useful to  learn because we can see exactly what save()/findAll() do behind.
spring.jpa.show-sql=true
