server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

  # Without proxy, web browser the backend throug port 8081. So it creates CORS problem. With the proxy, all goes over port 80, so no CORS.
      location /api/ {
            proxy_pass http://paperless-rest:8081;
        }
}

# We need two location, because one is for the API and one is for the React. /api/ goes to backend, so  nginx sends it to the backend
# remaining requests goes to React files.